Repository munich-quantum-toolkit/yaqs, pull requests merged in 2025-08, with the labels that each got.

#162 fixed improper evaluate at first timestep if sampling timesteps
  src/mqt/yaqs/analog/analog_tjm.py
  src/mqt/yaqs/core/data_structures/simulation_parameters.py
  tests/core/data_structures/test_simulation_parameters.py
Labels: bug

#163 added ability to stop progress bar from printing via SimParams initialization
  src/mqt/yaqs/core/data_structures/simulation_parameters.py
  src/mqt/yaqs/simulator.py
  tests/analog/test_analog_tjm.py
  tests/core/data_structures/test_networks.py
  tests/core/data_structures/test_simulation_parameters.py
  tests/core/methods/test_bug.py
  tests/core/methods/test_decompositions.py
  tests/core/methods/test_dissipation.py
  tests/core/methods/test_stochastic_process.py
  tests/core/methods/test_tdvp.py
  tests/digital/test_digital_tjm.py
  tests/test_simulator.py
Labels: feature

#165 ❤️ Add support option
  README.md
  docs/index.md
  docs/references.md
  docs/refs.bib
Labels: documentation
