Repository munich-quantum-toolkit/yaqs, pull requests merged in 2025-06, with the labels that each got.

#99 ⬆️ Update development dependencies and setup
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/release-drafter.yml
  .pre-commit-config.yaml
  .readthedocs.yaml
  pyproject.toml
  uv.lock
Labels: continuous integration, dependencies

#101 fixed bug in equivalence checking of long-range gates
  src/mqt/yaqs/circuits/utils/mpo_utils.py
  src/mqt/yaqs/core/libraries/gate_library.py
  tests/circuits/circuit.qasm
  tests/circuits/test_equivalence_checking.py
Labels: fix

#107 restructure package naming for analog and digital quantum simulation
  README.md
  docs/examples/analog_simulation.md
  docs/examples/fermi_hubbard_simulation.md
  docs/examples/strong_circuit_simulation.md
  docs/index.md
  src/mqt/yaqs/analog/__init__.py
  src/mqt/yaqs/analog/analog_tjm.py
  src/mqt/yaqs/core/data_structures/simulation_parameters.py
  src/mqt/yaqs/core/methods/bug.py
  src/mqt/yaqs/core/methods/tdvp.py
  src/mqt/yaqs/digital/__init__.py
  src/mqt/yaqs/digital/digital_tjm.py
  src/mqt/yaqs/digital/equivalence_checker.py
  src/mqt/yaqs/digital/utils/__init__.py
  src/mqt/yaqs/digital/utils/dag_utils.py
  src/mqt/yaqs/digital/utils/mpo_utils.py
  src/mqt/yaqs/simulator.py
  tests/analog/__init__.py
  tests/analog/test_analog_tjm.py
  tests/core/data_structures/test_simulation_parameters.py
  tests/core/methods/test_bug.py
  tests/core/methods/test_decompositions.py
  tests/core/methods/test_tdvp.py
  tests/digital/__init__.py
  tests/digital/circuit.qasm
  tests/digital/test_digital_tjm.py
  tests/digital/test_equivalence_checking.py
  tests/digital/utils/__init__.py
  tests/digital/utils/test_dag_utils.py
  tests/digital/utils/test_mpo_utils.py
  tests/test_simulator.py
Labels: enhancement, refactor

#106 added more noise processes and ability to fine-tune noise models locally
  docs/examples/analog_simulation.md
  docs/examples/strong_circuit_simulation.md
  docs/examples/weak_circuit_simulation.md
  src/mqt/yaqs/analog/analog_tjm.py
  src/mqt/yaqs/core/data_structures/noise_model.py
  src/mqt/yaqs/core/libraries/circuit_library.py
  src/mqt/yaqs/core/libraries/noise_library.py
  src/mqt/yaqs/core/methods/dissipation.py
  src/mqt/yaqs/core/methods/stochastic_process.py
  src/mqt/yaqs/digital/digital_tjm.py
  src/mqt/yaqs/simulator.py
  tests/analog/test_analog_tjm.py
  tests/core/data_structures/test_noise_model.py
  tests/core/methods/test_dissipation.py
  tests/core/methods/test_stochastic_process.py
  tests/test_simulator.py
Labels: feature
