Repository munich-quantum-toolkit/yaqs, pull requests merged in 2025-07, with the labels that each got.

#117 updated documentation
  docs/examples/analog_simulation.md
  docs/examples/equivalence_checking.md
  docs/examples/fermi_hubbard_simulation.md
  docs/examples/strong_circuit_simulation.md
  docs/examples/weak_circuit_simulation.md
  docs/references.md
  docs/refs.bib
Labels: bug, documentation

#125 🚸 Add changelog and upgrade guide
  CHANGELOG.md
  UPGRADING.md
  docs/CHANGELOG.md
  docs/UPGRADING.md
  docs/index.md
Labels: documentation

#123 👷 Enable templating
  .github/workflows/templating.yml
Labels: continuous integration
